// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"

	"github.com/lingojack/taobao_clone/config"
	"github.com/lingojack/taobao_clone/controller"
	"github.com/lingojack/taobao_clone/pkg/database"
	"github.com/lingojack/taobao_clone/pkg/logger"
	"github.com/lingojack/taobao_clone/pkg/validator"
	"github.com/lingojack/taobao_clone/router"
	"github.com/lingojack/taobao_clone/service"
)

func initEcho(cfgPath string) (*echo.Echo, func(), error) {
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	log := logger.New(cfg)
	db, cleanup, err := database.New(cfg, log)
	if err != nil {
		return nil, nil, err
	}

	// Services
	authService := service.NewAuthService(db, cfg)
	userService := service.NewUserService(db)
	productService := service.NewProductService(db)
	cartService := service.NewCartService(db)
	orderService := service.NewOrderService(db)
	favoriteService := service.NewFavoriteService(db)
	couponService := service.NewCouponService(db)
	shopService := service.NewShopService(db)

	// Controllers
	healthController := controller.NewHealthController()
	authController := controller.NewAuthController(authService)
	userController := controller.NewUserController(userService)
	productController := controller.NewProductController(productService)
	cartController := controller.NewCartController(cartService)
	orderController := controller.NewOrderController(orderService)
	favoriteController := controller.NewFavoriteController(favoriteService)
	couponController := controller.NewCouponController(couponService)
	shopController := controller.NewShopController(shopService)

	controllers := router.NewControllers(
		healthController,
		authController,
		userController,
		productController,
		cartController,
		orderController,
		favoriteController,
		couponController,
		shopController,
	)

	customValidator := validator.New()
	e, cleanup2, err := router.NewEcho(cfg, log, db, customValidator, controllers)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return e, func() {
		cleanup2()
		cleanup()
	}, nil
}
